<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        Ingredient::updateOrCreate(['name' => 'Abobrinha'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Batata Doce'], ['unit' => 'g', 'unit_cost' => 5.00, 'cost_per_unit' => 5.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Peito de Frango'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Carne Moída (Patinho)'], ['unit' => 'g', 'unit_cost' => 35.00, 'cost_per_unit' => 35.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Cenoura (c/ casca)'], ['unit' => 'g', 'unit_cost' => 4.50, 'cost_per_unit' => 4.50, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Aveia em Flocos'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Coração Bovino'], ['unit' => 'g', 'unit_cost' => 20.00, 'cost_per_unit' => 20.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Fígado Bovino'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Arroz Integral'], ['unit' => 'g', 'unit_cost' => 5.00, 'cost_per_unit' => 5.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Lombo Suíno'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 0.70, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Coração de Frango'], ['unit' => 'g', 'unit_cost' => 20.00, 'cost_per_unit' => 20.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Moela de Frango (s/ pele)'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Fígado de Frango'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Polpa de coco (fruta inteira ou ralada)'], ['unit' => 'g', 'unit_cost' => 35.00, 'cost_per_unit' => 35.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Papada de Frango'], ['unit' => 'g', 'unit_cost' => 10.00, 'cost_per_unit' => 10.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Costela'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 0.70, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Fígado Suíno'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Língua Bovino'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 0.70, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Coração Suíno'], ['unit' => 'g', 'unit_cost' => 20.00, 'cost_per_unit' => 20.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Músculo Bovino'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 0.70, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Carne Suína'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Músculo de Frango'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Pescoço de Frango'], ['unit' => 'g', 'unit_cost' => 10.00, 'cost_per_unit' => 10.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Proteína', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Colágeno em Pó'], ['unit' => 'g', 'unit_cost' => 150.00, 'cost_per_unit' => 150.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Suplemento', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Óleo de Coco'], ['unit' => 'ml', 'unit_cost' => 55.00, 'cost_per_unit' => 55.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Óleo de Girassol'], ['unit' => 'ml', 'unit_cost' => 20.00, 'cost_per_unit' => 20.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Óleo de Cártamo'], ['unit' => 'ml', 'unit_cost' => 40.00, 'cost_per_unit' => 40.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Azeite de Oliva extra virgem'], ['unit' => 'ml', 'unit_cost' => 80.00, 'cost_per_unit' => 80.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Gordura', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Cúrcuma'], ['unit' => 'g', 'unit_cost' => 35.00, 'cost_per_unit' => 35.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Outro', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Gengibre em pó'], ['unit' => 'g', 'unit_cost' => 45.00, 'cost_per_unit' => 45.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Outro', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Salsinha'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Ervilha Torta'], ['unit' => 'g', 'unit_cost' => 25.00, 'cost_per_unit' => 25.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Beterraba'], ['unit' => 'g', 'unit_cost' => 5.00, 'cost_per_unit' => 5.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Inhame'], ['unit' => 'g', 'unit_cost' => 8.00, 'cost_per_unit' => 8.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Mandioca'], ['unit' => 'g', 'unit_cost' => 6.00, 'cost_per_unit' => 6.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Chuchu'], ['unit' => 'g', 'unit_cost' => 4.00, 'cost_per_unit' => 4.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Batata Inglesa'], ['unit' => 'g', 'unit_cost' => 6.00, 'cost_per_unit' => 6.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Carboidrato', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Repolho'], ['unit' => 'g', 'unit_cost' => 4.00, 'cost_per_unit' => 4.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Couve-flor'], ['unit' => 'g', 'unit_cost' => 8.00, 'cost_per_unit' => 8.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Brócolis'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 0.80, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Vagem'], ['unit' => 'g', 'unit_cost' => 15.00, 'cost_per_unit' => 15.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Quiabo'], ['unit' => 'g', 'unit_cost' => 10.00, 'cost_per_unit' => 10.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Tomate Cereja'], ['unit' => 'g', 'unit_cost' => 18.00, 'cost_per_unit' => 18.00, 'loss_rate' => 0.95, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Berinjela'], ['unit' => 'g', 'unit_cost' => 6.00, 'cost_per_unit' => 6.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Alface Crespa'], ['unit' => 'g', 'unit_cost' => 8.00, 'cost_per_unit' => 8.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Rúcula'], ['unit' => 'g', 'unit_cost' => 10.00, 'cost_per_unit' => 10.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Espinafre'], ['unit' => 'g', 'unit_cost' => 12.00, 'cost_per_unit' => 12.00, 'loss_rate' => 0.85, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Couve Manteiga'], ['unit' => 'g', 'unit_cost' => 8.00, 'cost_per_unit' => 8.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Acelga'], ['unit' => 'g', 'unit_cost' => 6.00, 'cost_per_unit' => 6.00, 'loss_rate' => 0.90, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Rabanete'], ['unit' => 'g', 'unit_cost' => 10.00, 'cost_per_unit' => 10.00, 'loss_rate' => 0.95, 'difficulty_multiplier' => 1.000, 'category' => 'Vegetal', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Suplemento Food Dog'], ['unit' => 'g', 'unit_cost' => 250.00, 'cost_per_unit' => 250.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Suplemento', 'stock_quantity' => 1000, 'is_active' => true]);
        Ingredient::updateOrCreate(['name' => 'Suplemento Botica Pet'], ['unit' => 'g', 'unit_cost' => 200.00, 'cost_per_unit' => 200.00, 'loss_rate' => 1.00, 'difficulty_multiplier' => 1.000, 'category' => 'Suplemento', 'stock_quantity' => 1000, 'is_active' => true]);
    }
}
